name: Keploy CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: Books
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Omaa1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Flask Server
        env:
          DATABASE_URL: postgresql://postgres:Omaa1234@localhost:5432/Books
        run: |
          nohup python run.py &
          sleep 10

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=ae0e9303-1ed4-47bc-9c53-558e40e86644 --base-path=http://127.0.0.1:5000/books --cloud
